### ISSUE TITLE
few suggestions if you dont mind

### ISSUE THREAD

**Issue by livinhigh** [robinfriedli/botify#134]
If an option where you search for music and select the option from the list implemented would be great! check rythm bot!

When you use the play command, the song restarts always , please check on that. also it would be convenient if the play command adds a new sonf to the end of the queue instead of stopping the current music and playing the new song.

 😅 Thanks a lot!

**Comment by robinfriedli** [comment]
> search for music and select the option from the list

Just use the `select` argument.

> adds a new sonf to the end of the queue instead of stopping the current music

Just use the queue command.

> When you use the play command, the song restarts always

What.
