### ISSUE TITLE
Bot not responding to commands

### ISSUE THREAD

**Issue by DigitallyFidget** [robinfriedli/botify#136]
I have the bot all setup and running, but it seems to not respond to its commands in chat at all. It has proper server permissions, same as the official bot, and the role it's in also has proper permissions as well. It gave the Getting Started initial spiel when added into my server, but beyond that, it's just dead in server. Back end I can see it's interacting with the SQL server. Only warning in log is that discordbots.org is not setup, which is correct, I don't want this a public bot.

**Comment by robinfriedli** [comment]
also what branch master, a release branch or development/v2.0?

**Comment by DigitallyFidget** [comment]
I was trying the help command and on the release branch. I didn't change the prefix as I didn't see where to change it, nor did I see mention of where it's set at in the readme documentation.

**Comment by robinfriedli** [comment]
It's mentioned in the getting started message sent when inviting the bot to the guild for the first time and on [top.gg](https://top.gg/bot/483377420494176258). The default prefix is $botify and the prefix or property command can be used to change it.

**Comment by DigitallyFidget** [comment]
Recompiled and started it back up again and it appears to be working now. It's responding. I can't say for certain what the failure was. "$botify help" was unable to work before, but it's happily operating again.

**Comment by robinfriedli** [comment]
Odd. Are you sure the first startup was successful? Make sure the following messages were logged at info level:
```
[INFO ] 2020-09-03 14:25:46.142 [main] ShardManager - Login Successful!
[INFO ] 2020-09-03 14:25:46.521 [JDA [0 / 1] MainWS-WriteThread] WebSocketClient - Connected to WebSocket
[INFO ] 2020-09-03 14:25:46.769 [JDA [0 / 1] MainWS-ReadThread] JDA - Finished Loading!
...
[INFO ] 2020-09-03 14:25:48.583 [main] Botify - Registered listeners
[INFO ] 2020-09-03 14:25:48.584 [main] Launcher - All starters done
```
Note that in the default logging configuration of botify 1 messages from third party classes (i.e. outside the `net.robinfriedli.botify` package) are not appended to the log file, so the JDA messages do not appear in the log file. If those messages did not appear it was likely a connection issue with discord; in that case the bot would not have appeared as online. In any case I doubt it is an issue with botify but rather discord or perhaps your setup but it's hard to say more without additional info.

**Comment by DigitallyFidget** [comment]
I think it was user error to some degree. The bot did come online, but when closed it went away and not offline the first run. It's working now though. I'm still unsure what happened, but it seems the fix was really just the classic IT solution of turn it off and back on again.
