### ISSUE TITLE
Needed Extra Permissions

### ISSUE THREAD

**Issue by Jaelabi** [robinfriedli/botify#140]
Hello!

I tried to enter a command, and then was given a response that said I needed to give botify permission to read message history.  It asked for a permission that wasn't automatically given when I first invited it to the server.

**Comment by robinfriedli** [comment]
Permissions are never given "automatically". If you used the invite link from top.gg or the readme page then all needed permissions are given, including reading messages. This does not affect channel specific permission overrides though so check those.

**Comment by Jaelabi** [comment]
I understand that permissions are not automatic, but when I used the invite link from top.gg, it still asked for additional permissions.  I have not set up any channel specific permission overrides, so that should not have been an issue.

**Comment by robinfriedli** [comment]
I've set up a fresh server and used the invite link on top.gg but could not reproduce the issue. When exactly did this issue occur / what command did you enter?

**Comment by Jaelabi** [comment]
Hello.  Sorry for not replying faster.

After I had first invited the bot to rmy server (and accepting all the permissions in the invite link from top.gg), the top.gg permission only asked for "Read messages," but when I first tried using it in my server (probably just $botify play), I was told to also give permission for "Read message history" as well.

I also tried to see if I could replicate it on another server, but the issue didn't occur again.  I'm not sure what could have been the issue, but it seems to not be happening any more, so I'm going to close this.

Thank you!

**Comment by robinfriedli** [comment]
Hmm well I haven't changed the invite link and it still does not include the read message history permission. The bot never uses the message history and should not require this permission. Not sure what happened there but it might have been a discord issue. Either way I'm glad to hear it works now.
