### ISSUE TITLE
Cannot login to the spotify...

### ISSUE THREAD

**Issue by jonzenor** [robinfriedli/botify#142]
I tried to start playing a station, and the bot told me that I was not logged in (despite logging in earlier in the week). I tried to login again, was sent the spotify link and clicked on the accept button, but was returned to the web with the following error:

`This site can’t be reached
botify.gg.robinfriedli.net refused to connect.`

I then tried to start playing music again and was still told that I am not logged in.

**Comment by robinfriedli** [comment]
Yeah there's a server issue with the public botify instance atm (btw please refer to the support guild for issues with the public instance, invite link's on the [top.gg page](https://top.gg/bot/483377420494176258) -> "join support server"). I'll restart the bot along with an increase of the server pool size (PR #141) and other improvements by Tuesday.

**Comment by robinfriedli** [comment]
Also btw you don't need to be logged in to play music. I presume you used the `$own` to search an item in your library, alternatively you can just paste the open.spotify link or Spotify URI for that playlist / album / track.
