### ISSUE TITLE
what should i do?

### ISSUE THREAD

**Issue by shawn3308** [robinfriedli/botify#196]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project botify: Fatal error compiling: invalid target release: 11 -> [Help 1]
![image](https://user-images.githubusercontent.com/60691117/103444590-8b895680-4c8f-11eb-8838-20002f6325f3.png)

**Comment by robinfriedli** [comment]
Make sure you're running java 11 (check `java -version` or `mvn -version` to see what version maven is using). Maybe use a tool like [jenv](https://www.jenv.be/) to manage java installations (don't forget to enable the maven plugin `jenv enable-plugin maven`).

**Comment by shawn3308** [comment]
do you have discord

**Comment by robinfriedli** [comment]
There's a botify support [server](https://discord.com/invite/gdc25AG). Also attach the full logs, preferably as a code snippet.
