### ISSUE TITLE
Playing album

### ISSUE THREAD

**Issue by pachecoke** [robinfriedli/botify#224]
I noticed that when using the Spotify search syntax for an album, it will only play the first song in the album.
Is it possible to play the entire album (like a playlist) if no song is specified?

For example:

$botify play $spotify artist:linkin park album:meteora

Otherwise, I don't see a way to play an entire album without first going to Spotify and adding the album to a private playlist.

We've been really enjoying the bot so far!

**Comment by robinfriedli** [comment]
By default the bot searches a track when the `$spotify` argument is used. `artist:` and `album:` are merely filters applied to the search query (see the section regarding field filters on the [Spotify API documentation](https://developer.spotify.com/documentation/web-api/reference/#endpoint-search)), not specifiers describing what the bot should search. To search for a Spotify album, use the `$album` argument, e.g. `play $spotify $album meteora artist:linkin park`. Btw you can also use the Spotify URI or open.spotify URL, e.g. `play spotify:album:4Gfnly5CzMJQqkUFfoHaP3` or `play https://open.spotify.com/album/4Gfnly5CzMJQqkUFfoHaP3?si=2Giu3i6uTyiKgtesrd7jDw` respectively.

**Comment by robinfriedli** [comment]
Also, spotify is the default source, so unless you've configured the `default source` property (using the property command or by changing the default value in the configuration file), the `$spotify` argument is not required.

**Comment by pachecoke** [comment]
Thank you! This was very useful and answered my question.
