### ISSUE TITLE
Unable to run project

### ISSUE THREAD

**Issue by gupta-shrinath** [robinfriedli/botify#225]
I have installed all the necessary softwares and followed all the steps but the localhost:8000 shows 404 not found No context found for request and log found in resources/logs are as follows

`[INFO ] 2021-02-18 00:08:04.327 [net.robinfriedli.botify.boot.Launcher.main()] Launcher - Using java version 11.0.10+8-LTS-162
[WARN ] 2021-02-18 00:08:09.287 [net.robinfriedli.botify.boot.Launcher.main()] Launcher - discordbots.org api not set up, missing properties
[INFO ] 2021-02-18 00:08:09.353 [net.robinfriedli.botify.boot.Launcher.main()] Launcher - Using NativeAudioSendFactory with a buffer duration of 400ms
[INFO ] 2021-02-18 00:08:11.809 [net.robinfriedli.botify.boot.Launcher.main()] RunLiquibaseUpdateTask - Beginning liquibase update
[INFO ] 2021-02-18 00:08:14.663 [net.robinfriedli.botify.boot.Launcher.main()] RunLiquibaseUpdateTask - Liquibase update done
[INFO ] 2021-02-18 00:08:15.099 [net.robinfriedli.botify.boot.Launcher.main()] Botify - Registered listeners
[INFO ] 2021-02-18 00:08:15.100 [net.robinfriedli.botify.boot.Launcher.main()] Launcher - All starters done
`

**Comment by robinfriedli** [comment]
You're running botify 1, there is no HttpHandler registered on the root path there, try /login, /list or /queue via the links shown by the login, queue or `search $list mylist` ccommands. See the `resources/xml-contributions/httpHandlers.xml` file for available http contexts.

**Comment by gupta-shrinath** [comment]
![image](https://user-images.githubusercontent.com/42563130/108316575-147a3400-71e3-11eb-9e9e-03f205653e83.png)
Thanks for the reply but  /login shows missing parameter
