### ISSUE TITLE
Cannot find symbol class Botify

### ISSUE THREAD

**Issue by liscuate** [robinfriedli/botify#227]
Error happens at: `import net.robinfriedli.botify.Botify;`

Screenshot of error:
![Capture](https://user-images.githubusercontent.com/25440248/109034303-cde77680-76c7-11eb-807f-caeb9cfead0e.PNG)

**Comment by robinfriedli** [comment]
This looks like IDE output? Make sure you've configured the maven / gradle project correctly (depending on botify 1 / 2). If you're using IntelliJ try right clicking the pom.xml / build.gradle file and selecting import as maven / gradle project. Also make sure you've set up the project sdk (preferably jdk 11).
