### ISSUE TITLE
youtube playlist with "unplayable songs" results in crash

### ISSUE THREAD

**Issue by kuschinockl** [robinfriedli/botify#233]
Dear botify team / robinfriedli,

we created a youtube playlist and wanted to play it with the botify bot on our discord server. At first, this went very well, no problems. However, yesterday the bot crashed due to "too many unplayable songs" in the queue and we could not get it running again. It also doesn't tell us, which songs are the problem, we would probably have to delete individual songs and each time try again if it works. Do you know a quick fix for this? The error message screenshot is attached.

Best wishes,
kuschinockl

![Bildschirmfoto 2021-03-03 um 21 22 58](https://user-images.githubusercontent.com/58085049/109873221-c1d25a80-7c6d-11eb-867f-92e12d2695a5.png)

**Comment by robinfriedli** [comment]
That's a lavaplayer issue. YouTube is changing stuff again, causing some scarping to fail. Iirc it has something to do with the load next endpoint for playlists changing.

**Comment by robinfriedli** [comment]
So to clarify, this affects any YouTube playlist that requires pagination, iirc more than 100 vids

**Comment by robinfriedli** [comment]
Also, the relevant lavaplayer issue can be found [here](https://github.com/sedmelluq/lavaplayer/issues/591)

**Comment by kuschinockl** [comment]
thanks for the info (:
