### ISSUE TITLE
Message returned by source: no PLAYER_JS_URL in youtube root EID: 8bdc6350-c058-46ba-8653-8c5c12bb65be, html<redacted>

### ISSUE THREAD

**Issue by ProxyPing** [robinfriedli/botify#242]
I got this error like if i want to play any track and i did not change anyhting in the code.
just the normal setup like bot token etc..

and heres the console error:

https://pastebin.com/k2i3azkG

**Comment by robinfriedli** [comment]
Looks like the pastebin expired. Is your clone up to date?

**Comment by ProxyPing** [comment]
Oh sry.. here is my paste server..
and yeah its up to date..

https://paste.proxyping.de/rorafapeyo.pl

**Comment by robinfriedli** [comment]
That can't be the latest build since lavaplayer is currently at 1.3.76 while you're on lavaplayer 1.3.73. Try pulling and rebuilding your jar.

**Comment by ProxyPing** [comment]
hm.. alright.. i will try that give me a moment..

**Comment by robinfriedli** [comment]
Does it work now?  🙂

**Comment by ProxyPing** [comment]
yeep thx this was my failure...

**Comment by ProxyPing** [comment]
but what can i do to this..

```
There has been an API error while loading some tracks. Please try again.
Exception
GoogleJsonResponseException: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.
CommandContext ID
d00d71d6-d178-455e-8077-09983ffab849
```

**Comment by robinfriedli** [comment]
Make sure the `YOUTUBE_API_DAILY_QUOTA` property in resources/settings.properties (or for botify 2 the property `botify.preferences.youtube_api_daily_quota` in src/main/resources/application.properties) is set to the quota you were given for your YouTube Data API project so that the bot can limit usage of the API accordingly.

**Comment by ProxyPing** [comment]
it is set to 10000, the normal limit..

**Comment by robinfriedli** [comment]
When I created my project YouTube gave me 1000000, 10000 is very low. That's worth 100 search requests. Was the quota limit property set correctly the whole time or have you just set it now? Have you seen a message logged by the YouTubeService when exceeding the quota and what's the output of the `youtube quota` command? Quota resets at midnight pacific time, if you find yourself hitting the limit in the future you could just further limit the quota limit property so botify stops using the API and falls back to crawling html pages earlier.

**Comment by ProxyPing** [comment]
Yes I have set the quota limit from the beginning to 10000 and the command shows me this: https://upload.proxyping.de/rCaM7bTzKxW5Ceq.png

**Comment by robinfriedli** [comment]
Looks good. If you run into a quota limit again in the future consider further lowering the limit. If the quota is 50k or below botify stops using the YouTube API where possible upon reaching 50% of the quota usage (else it's 75%) but note that searching YouTube playlist always requires using the API.

**Comment by ProxyPing** [comment]
I have another question, the bot is lagging very much but the bot is on a strong server....

**Comment by ProxyPing** [comment]
it runs on an linux system, and no there is no packet loss.. 
Screenshot of usage: https://suka.blyat.xyz/uploads/16f694f5-a0eb-438f-8929-e0087ce66df2/18hnMBfN_.png

analytics command: https://suka.blyat.xyz/uploads/16f694f5-a0eb-438f-8929-e0087ce66df2/SLFqGAz8_.png

**Comment by robinfriedli** [comment]
You still haven't answered how many guilds are playing concurrently, if you're using a native buffer (`NATIVE_AUDIO_BUFFER` / `botify.preferences.native_audio_buffer` property) and whether you're using botify 1 or 2. And how did you check for packet loss? Can probably rule out CPU or memory usage, provided those screenshots were taken while there was stuttering.
