### ISSUE TITLE
Disable IPV6 rotator

### ISSUE THREAD

**Issue by joaquinv98** [robinfriedli/botify#243]
Is there a way to disable the IPV6 need to run the bot?

**Comment by robinfriedli** [comment]
There's no need at all, just leave the `IPV6_BLOCKS` property empty (or the `botify.preferences.ipv6_blocks` for botify 2).

**Comment by joaquinv98** [comment]
I'm not in the PC right now, but when I do that I get an error, something about that I should use a placeholder then I tried to put there the cloudflare ipv6 dns and get another error about the range, it asked me for bigger blocks, finally added "/64" in the end of the dns and the not starts but when I try to play music y get an error that It can't resolve the ipv6. 
Maybe it is related to my environment for the bot, I'm using it in pterodactyl panel, inside a docker container and it literally doesn't have ipv6

**Comment by robinfriedli** [comment]
Just leave it empty exactly how it was when you cloned it.

**Comment by joaquinv98** [comment]
So, the first msj was because i didn't have the field at all. fixed leaving it empty
