### ISSUE TITLE
Botify don't report executed commands in the chat

### ISSUE THREAD

**Issue by Musical797** [robinfriedli/botify#244]
When I run a command the bot recognizes and executes the command, but don't give any writen or visual feedback as it used to do.

**Comment by robinfriedli** [comment]
Cloudflare Ratelimit likely caused by receiving too many 403s from YouTube, should be back up. For issues specific to the public instance please use the [discord server](https://discord.com/invite/gdc25AG)

**Comment by Musical797** [comment]
Everything is fine now. Thanks a lot
