### ISSUE TITLE
Can't play own playlists anymore

### ISSUE THREAD

**Issue by JackalGhul1623** [robinfriedli/botify#257]
Hello, i can't use the $own command anymore.

Everything else works fine except when i try to use my own spotify playlists with the command :

$botify play $spotify $list $own playlist name

I get this message from the bot :

Exception
NullPointerException: null
CommandContext ID
5730c06d-eb07-4f26-a9f0-50a403236fd7

Am i doing something wrong ?

(i already checked that i am logged with the bot and still not working)

**Comment by robinfriedli** [comment]
Still the same old spotify api issue https://github.com/spotify-web-api-java/spotify-web-api-java/issues/241, will just have to restart the bot

**Comment by JackalGhul1623** [comment]
> Still the same old spotify api issue [spotify-web-api-java/spotify-web-api-java#241](https://github.com/spotify-web-api-java/spotify-web-api-java/issues/241), will just have to restart the bot

I am sorry to take your time like this, but i have very little programming skills, could you tell me how you restart the bot please ?

**Comment by robinfriedli** [comment]
Not sure if you're self hosting or talking about the public instance. In case it's the latter, I've already restarted that.

**Comment by JackalGhul1623** [comment]
Oh it's working now... so you have to do it from your side... so... should we notify you each time this happen ?

**Comment by robinfriedli** [comment]
Indeed, preferrably via the support discord :)

**Comment by JackalGhul1623** [comment]
> Indeed, preferrably via the support discord :)

Roger roger

**Comment by JackalGhul1623** [comment]
> Indeed, preferrably via the support discord :)

Actually i can't find the Discord XD, could you give me an invite or something ?

**Comment by robinfriedli** [comment]
Sure here's the [invite link](https://discord.com/invite/gdc25AG) from top.gg
