### ISSUE TITLE
Possible to create shortcuts??

### ISSUE THREAD

**Issue by Hamuelin** [robinfriedli/botify#263]
Tried to create shortcuts for commands such as !p instead of !play, !q instead of !queue, !s instead of skip etc. etc. (I've changed the prefix to !). 

I can't see any way to create these shortcuts. I tried to see if the preset feature would allow that, but I must be getting something wrong with the syntax, or the feature doesn't allow it. 

I thought it would've been as simple as "!preset play !as p" (again, I've changed both prefix to !). But it tells me preset does not have a variable.

**Comment by robinfriedli** [comment]
If your preset takes command input you need the %s formatter, so it's `!preset play %s !as p`, that means input is not necessarily appended at the end, for example you could do `!preset "add %s !to favs" !as fav`, to then be able to type `fav !album meteora` to add album meteora to playlist favs.
